  deploy:
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Kubernetes manifests
        run: |
          kubectl version --client
          kubectl apply --dry-run=client -f k8s/namespace.yaml
          kubectl apply --dry-run=client -f k8s/secret.yaml
          kubectl apply --dry-run=client -f k8s/postgres.yaml
          kubectl apply --dry-run=client -f k8s/backend.yaml
          kubectl apply --dry-run=client -f k8s/frontend.yaml
          kubectl apply --dry-run=client -f k8s/ingress.yaml
          kubectl apply --dry-run=client -f k8s/grafana-ingress.yaml